[package]
name = "foamcore"
version = "0.1.0"
authors = ["Jun Zhu <jun.zhu@psi.ch>"]
license = "BSD-3-Clause"
edition = "2021"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
zmq = "0.10.0"
redis = "0.23.2"
serde_json = "1.0.104"
apache-avro = "0.15.0"
thiserror = "1.0.47"